// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqV1oI7lRQgEgLIg65lkyPdWlh0wnqn-8',
    appId: '1:498183924736:web:7cf598d4d543b22e23bce5',
    messagingSenderId: '498183924736',
    projectId: 'hw-4-55495',
    authDomain: 'hw-4-55495.firebaseapp.com',
    storageBucket: 'hw-4-55495.firebasestorage.app',
    measurementId: 'G-YP7MEG1BQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIE-6lmpKgQGayPfbDhLIApSTf0UgvFa0',
    appId: '1:498183924736:android:217b0a4c8b06cc8e23bce5',
    messagingSenderId: '498183924736',
    projectId: 'hw-4-55495',
    storageBucket: 'hw-4-55495.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr1icc88888Kgd_0iteyS3bKzBWbCNA7w',
    appId: '1:498183924736:ios:7c12cb87bed63c4b23bce5',
    messagingSenderId: '498183924736',
    projectId: 'hw-4-55495',
    storageBucket: 'hw-4-55495.firebasestorage.app',
    iosBundleId: 'com.example.messageBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr1icc88888Kgd_0iteyS3bKzBWbCNA7w',
    appId: '1:498183924736:ios:7c12cb87bed63c4b23bce5',
    messagingSenderId: '498183924736',
    projectId: 'hw-4-55495',
    storageBucket: 'hw-4-55495.firebasestorage.app',
    iosBundleId: 'com.example.messageBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqV1oI7lRQgEgLIg65lkyPdWlh0wnqn-8',
    appId: '1:498183924736:web:9b822ccc19b4d03523bce5',
    messagingSenderId: '498183924736',
    projectId: 'hw-4-55495',
    authDomain: 'hw-4-55495.firebaseapp.com',
    storageBucket: 'hw-4-55495.firebasestorage.app',
    measurementId: 'G-EZVEJE18J4',
  );
}
